local Translations = {
    error = {
        no_item = 'Falta %{item}!',
        no_chemicals = "Está faltando produtos químicos!",
        no_trimming_scissors = "Você precisará de tesouras de poda para isso!",
        no_coca_leaf = "Você precisa de folhas de coca!",
        no_bakingsoda_amount = "Você precisará de %{value} bicarbonato de sódio!",
        no_bakingsoda = "Você precisará de bicarbonato de sódio!",
        no_cokain_amount = "Você precisará de %{value} cocaína!",
        no_cokain = "Você precisará de cocaína!",
        not_all_items = "Você não possui todos os itens necessários!",
        already_processing = "Você já está processando algo!",
        not_enough_small_bricks = "Você precisa de %{value} pacotes pequenos de cocaína!",
        no_poppy_resin = "Você não possui resina de papoula!",
        no_lsa = "Está faltando LSA!",
        no_thionyl_chloride = "Está faltando cloreto de tionila!",
        too_far = "O processamento foi cancelado porque você saiu da área!",
        no_sulfuric_acid = "Está faltando ácido sulfúrico!",
        no_hydrochloric_acid = "Está faltando ácido clorídrico!",
        no_sodium_hydroxide = "Está faltando hidróxido de sódio!",
        no_liquidmix = "Está faltando mistura química líquida!",
        no_chemicalvapor = "Está faltando vapores químicos!",
        no_methtray = "Está faltando uma bandeja de metanfetamina!",
        no_cannabis = "Está faltando cannabis!",
        no_marijuhana = "Está faltando maconha!",
        enough_temp = "A temperatura já está adequada!",
        temp_too_low = "A temperatura estava muito baixa. A mistura agora não é utilizável!",
        temp_too_high = "A temperatura estava muito alta. A mistura agora não é utilizável!",
    },
    success = {
        temp_up = "Temperatura aumentada!",
        temp_down = "Temperature reduzida!",
        hydrochloric_acid = "O processo com ácido clorídrico foi bem-sucedido!",
        sodium_hydroxide = "O processo com hidróxido de sódio foi bem-sucedido!",
        sulfuric_acid = "O processo com ácido sulfúrico foi bem-sucedido!",
        lsa = "O processo com LSA foi bem-sucedido!",
        coke = "Folhas de coca processadas com sucesso!",
        coke_small_brick = "Cocaína cortada em pequenos tijolos com sucesso!",
        coke_brick = "Pacote de cocaína prensado para distribuição!",
        heroin = "Heroína processada com sucesso!",
        thionyl_chloride = "Tionil cloreto processado com sucesso!",
        meth = "Meth produzido com sucesso!",
        chemicals = "Produtos químicos coletados com sucesso!",
        coca_leaf = "Folhas de coca coletadas",
        poppyresin = "Resina de papoula coletada com sucesso!",
        lsd = "LSD produzido com sucesso!",
        cannabis = "Cannabis coletada com sucesso!",
        marijuana = "Marijuana produzida com sucesso!",
        joint = "Você enrolou um baseado com sucesso!",
        baggy = "Você embalou um pouco de skunk com sucesso!",
    },
    info = {

    },
    progressbar = {
        processing = "Processessando...",
        packing = "Embalando...",
        collecting = "Coletando......",
        pickup_chemicals = "Pegando...",
        temp_up = "Aumentando a temperatura",
        temp_down = "Reduzindo a temperatura",
        rolling_joint = "Enrolando um baseado",
        bagging_skunk = "Embalando skunk",
    },
    items = {
        hydrochloric_acid = "Ácido clorídrico",
        sodium_hydroxide = "Hidróxido de sódio",
        sulfuric_acid = "Ácido sulfúrico",
        lsa = "LSA",
        coca_leaf = "Folha de coca",
        trimming_scissors = "Tesoura de poda",
    },
    menu = {
        chemMenuHeader = "Menu de Química",
        chemicals = "x1 Produtos Químicos",
        close = "Fechar",
        closetxt = "Fechar menu",
    },
    target = {
        process_thionyl_chloride = "Processar cloreto de tionila",
        talk_to_walter = "Falar com Walter",
        talk_to_draco = "Falar com Draco",
        talk_to_charlotte = "Falar com Charlotte",
        chemmenu = "Compostos químicos",
        methprocess = "Preparar algo maravilhoso e azul",
        methtempup = "Aumentar temperatura",
        methtempdown = "Diminuir temperatura",
        bagging = "Empacotando",
        keypad = "Sair do laboratório",
        cokeleafproc = "Processar",
        cokepowdercut = "Refinar",
        weedproces = "Cortar e secar",
        heroinproces = "Processar",
        heroinproc = "Processar",
        pickCocaLeaves = "Coletar",
        pickHeroin = "Coletar",
        pickWeed = "Coletar",
        pickSodium = "Pegar",
        pickSulfuric = "Pegar",
        pickChemicals = "Pegar",
        hydrochloricacid = "Pegar",
    },
    drawtext = {
        process_lsd = "~g~E~w~ - Processar",
    },
}

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})
