local Translations = {
    weather = {
        now_frozen = 'O clima está congelado agora.',
        now_unfrozen = 'O clima não está mais congelado.',
        invalid_syntax = 'Sintaxe inválida, a sintaxe correta é:: /weather <tipodeclima> ',
        invalid_syntaxc = 'Sintaxe inválida, use /weather <tipodeClima> em vez disso!',
        updated = 'O clima foi atualizado.',
        invalid = 'Tipo de clima inválido, os tipos de clima válidos são:  \nEXTRASUNNY CLEAR NEUTRAL SMOG FOGGY OVERCAST CLOUDS CLEARING RAIN THUNDER SNOW BLIZZARD SNOWLIGHT XMAS HALLOWEEN ',
        invalidc = 'Tipo de clima inválido, os tipos de clima válidos são: \nEXTRASUNNY CLEAR NEUTRAL SMOG FOGGY OVERCAST CLOUDS CLEARING RAIN THUNDER SNOW BLIZZARD SNOWLIGHT XMAS HALLOWEEN ',
        willchangeto = 'O clima mudará para: %{value}.',
        accessdenied = 'Acesso negado para o comando /weather.',
    },
    dynamic_weather = {
        disabled = 'As mudanças de clima dinâmico estão agora desativadas.',
        enabled = 'As mudanças de clima dinâmico estão agora ativadas.',
    },
    time = {
        frozenc = 'O tempo está agora congelado.',
        unfrozenc = 'O tempo não está mais congelado.',
        now_frozen = 'O tempo está agora congelado.',
        now_unfrozen = 'O tempo não está mais congelado.',
        morning = 'Tempo definido para manhã.',
        noon = 'Tempo definido para meio-dia.',
        evening = 'Tempo definido para tarde.',
        night = 'Tempo definido para noite.',
        change = 'O tempo mudou para %{value}:%{value2}.',
        changec = 'O tempo foi alterado para: %{value}!',
        invalid = 'Sintaxe inválida, a sintaxe correta é:  time <hora> <minuto> !',
        invalidc = 'Sintaxe inválida. Use /time <hora> <minuto> em vez disso!',
        access = 'Acesso negado para o comando /time.',
    },
    blackout = {
        enabled = 'O apagão agora está ativado.',
        enabledc = 'O apagão agora está ativado.',
        disabled = 'O apagão agora está desativado.',
        disabledc = 'O apagão agora está desativado.',
    },
    help = {
        weathercommand = 'Alterar o clima.',
        weathertype = 'tipodeclima',
        availableweather = 'Tipos disponíveis: extrasunny, clear, neutral, smog, foggy, overcast, clouds, clearing, rain, thunder, snow, blizzard, snowlight, xmas & halloween',
        timecommand = 'Alterar o tempo.',
        timehname = 'horas',
        timemname = 'minutos',
        timeh = 'Um número entre 0 - 23',
        timem = 'Um número entre 0 - 59',
        freezecommand = 'Congelar/descongelar o tempo.',
        freezeweathercommand = 'Ativar/desativar mudanças dinâmicas de clima.',
        morningcommand = 'Definir o tempo para 09:00',
        nooncommand = 'Definir o tempo para 09:00',
        eveningcommand = 'Definir o tempo para 18:00',
        nightcommand = 'Definir o tempo para 23:00',
        blackoutcommand = 'Alternar o modo de apagão.',
    },
}

Lang = Lang or Locale:new({
    phrases = Translations,
    warnOnMissing = true
})
